version: "3.9"

services:
  db:
    image: postgres:15
    container_name: orbe-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BRM
      POSTGRES_DB: orbe
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: orbe-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release

volumes:
  pgdata:
